name: symbolize
version: '1.0'
summary: Keep your configuration files synced between workstations using symbolic
  links
description: |
  Use this with ex. Dropbox to keep your configuration files synced between
  your workstations using symbolic links

  I was inspired by Ira's mackup, but I needed to have some configuration
  files shared between all my computers (ex. ~/.vimrc), and some available
  in Dropbox under their own hostname folders for backup-purpose (ex. ~/.ssh).
  
  https://github.com/SlimG/symbolize
type: app
architectures:
- all
confinement: strict
grade: stable
apps:
  symbolize:
    command: bin/symbolize
parts:
  symbolize:
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      cp symbolize $SNAPCRAFT_PART_INSTALL/bin/
